// Unit tests for scripts/release-checksum.mjs (issue #69): the SHA-256
// sidecar logic for release assets. The pure core is exercised without
// touching the filesystem where possible; the file-level operations
// (writeChecksum / checkChecksum) run against a temp dir because they
// are the operations the release workflow actually invokes.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';

import {
  sha256OfFile,
  checksumLine,
  parseChecksumFile,
  verifyDigests,
  writeChecksum,
  checkChecksum,
} from '../scripts/release-checksum.mjs';

// A known vector so a regression to a different hash or encoding is
// caught without recomputing expectations by hand.
const KNOWN_HEX = createHash('sha256').update('queryhop fixture').digest('hex');

test('sha256OfFile matches node:crypto for a known string', () => {
  assert.equal(sha256OfFile(Buffer.from('queryhop fixture')), KNOWN_HEX);
  assert.match(sha256OfFile(new Uint8Array(0)), /^[0-9a-f]{64}$/);
});

test('checksumLine emits the shasum text-mode format (hex + two spaces)', () => {
  assert.equal(
    checksumLine(KNOWN_HEX, 'QueryHop-1.0.3-macos-universal-unsigned.zip'),
    `${KNOWN_HEX}  QueryHop-1.0.3-macos-universal-unsigned.zip\n`
  );
});

test('checksumLine rejects non-SHA-256 digests', () => {
  assert.throws(() => checksumLine('abc', 'x.zip'), /not a SHA-256/);
  assert.throws(() => checksumLine('Z'.repeat(64), 'x.zip'), /not a SHA-256/);
});

test('parseChecksumFile accepts text-mode, binary-mode, comments and blank lines', () => {
  const content = [
    `# generated by scripts/release-checksum.mjs`,
    '',
    `${KNOWN_HEX}  QueryHop-1.0.2-macos-universal-unsigned.zip`,
    `${KNOWN_HEX} *QueryHop-1.0.2-macos-universal.zip`,
    '',
  ].join('\n');
  const r = parseChecksumFile(content);
  assert.ok(r.ok, r.errors.join('; '));
  assert.equal(r.entries.length, 2);
  assert.equal(r.entries[0].binary, false);
  assert.equal(r.entries[1].binary, true);
  assert.equal(r.entries[0].filename, 'QueryHop-1.0.2-macos-universal-unsigned.zip');
});

test('parseChecksumFile reports malformed lines and empty files', () => {
  const bad = parseChecksumFile('not a checksum line');
  assert.equal(bad.ok, false);
  assert.match(bad.errors[0], /line 1/);
  const empty = parseChecksumFile('');
  assert.equal(empty.ok, false);
  assert.match(empty.errors[0], /empty/);
});

test('verifyDigests matches, detects mismatches and missing files', () => {
  const entries = [
    { hex: KNOWN_HEX, binary: false, filename: 'a.zip' },
    { hex: KNOWN_HEX, binary: false, filename: 'b.zip' },
  ];
  assert.ok(verifyDigests(entries, { 'a.zip': KNOWN_HEX, 'b.zip': KNOWN_HEX }).ok);

  const mismatch = verifyDigests(entries, { 'a.zip': '0'.repeat(64), 'b.zip': KNOWN_HEX });
  assert.equal(mismatch.ok, false);
  assert.match(mismatch.errors[0], /MISMATCH: a\.zip/);

  const missing = verifyDigests(entries, { 'a.zip': KNOWN_HEX });
  assert.equal(missing.ok, false);
  assert.match(missing.errors[0], /no file to verify: b\.zip/);
});

test('writeChecksum creates a verifiable sidecar; tampering is detected', () => {
  const dir = mkdtempSync(path.join(tmpdir(), 'queryhop-sha-'));
  try {
    const zip = path.join(dir, 'QueryHop-1.0.3-macos-universal-unsigned.zip');
    writeFileSync(zip, 'release payload');
    const r = writeChecksum(zip);
    assert.ok(r.ok, r.errors.join('; '));
    assert.equal(r.hex, createHash('sha256').update('release payload').digest('hex'));
    assert.ok(readFileSync(r.outPath, 'utf8').endsWith('QueryHop-1.0.3-macos-universal-unsigned.zip\n'));

    // The stock-tool round trip: the file must verify as-is...
    assert.ok(checkChecksum(r.outPath).ok);

    // ...and must fail after any byte of the artifact changes.
    writeFileSync(zip, 'release payload!');
    const tampered = checkChecksum(r.outPath);
    assert.equal(tampered.ok, false);
    assert.match(tampered.errors[0], /MISMATCH/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('writeChecksum / checkChecksum fail cleanly on missing inputs', () => {
  const r = writeChecksum('/nonexistent/queryhop-missing.zip');
  assert.equal(r.ok, false);
  assert.match(r.errors[0], /not found/);

  const c = checkChecksum('/nonexistent/queryhop-missing.zip.sha256');
  assert.equal(c.ok, false);
  assert.match(c.errors[0], /not found/);
});
